Repository sealsystems/node-tlscert, pull requests merged in 2023-05, with the labels that each got.

#501 Update build configuration
  package-lock.json
Labels: automatic-merge

#503 Update build configuration
  packaging/linux/rpm/build.sh
  packaging/linux/rpm/resource/start_no_envconsul.sh
  packaging/windows/msi/build.ps1
  packaging/windows/msi/resource/run_no_envconsul.bat
Labels: automatic-merge

#504 Update build configuration
  package-lock.json
Labels: automatic-merge

#505 feat: new function getExternal
  lib/tlscert.js
  test/keyCertCaExt/ca.pem
  test/keyCertCaExt/cert.pem
  test/keyCertCaExt/key.pem
  test/tlscertTest.js
Labels: release/minor, release/feat

#506 chore: Update update-build-config.yml
  .github/workflows/update-build-config.yml
Labels: release/patch, release/chore

#508 chore: fixed repo type
  .github/workflows/publish-on-npmjs-org.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/trigger-release-on-nodejs-update.yml
  .github/workflows/update-dependencies.yml
  .npmignore
  .vscode/launch.json
  LICENSE
  package-lock.json
  package.json
Labels: release/patch, release/chore

#507 Update build configuration
  package-lock.json
Labels: automatic-merge

#509 Update build configuration
  package-lock.json
Labels: automatic-merge

#510 Update build configuration
  package-lock.json
Labels: automatic-merge

#511 Update build configuration
  package-lock.json
Labels: automatic-merge

#512 Update build configuration
  package-lock.json
Labels: automatic-merge

#513 Update build configuration
  package-lock.json
Labels: automatic-merge

#514 Update build configuration
  package-lock.json
Labels: automatic-merge

#515 Update build configuration
  package-lock.json
Labels: automatic-merge

#516 Update build configuration
  package-lock.json
Labels: automatic-merge

#517 Update build configuration
  package-lock.json
Labels: automatic-merge

#518 Update build configuration
  package-lock.json
Labels: automatic-merge

#519 Update build configuration
  package-lock.json
Labels: automatic-merge

#520 Update build configuration
  package-lock.json
Labels: automatic-merge

#521 Update build configuration
  package-lock.json
Labels: automatic-merge

#522 Update build configuration
  package-lock.json
Labels: automatic-merge

#523 Update build configuration
  package-lock.json
Labels: automatic-merge

#525 Update build configuration
  package-lock.json
Labels: automatic-merge

#526 Update build configuration
  package-lock.json
Labels: automatic-merge

#527 Update build configuration
  package-lock.json
Labels: automatic-merge

#528 Update build configuration
  package-lock.json
Labels: automatic-merge

#529 Update build configuration
  package-lock.json
Labels: automatic-merge

#531 Update build configuration
  package-lock.json
Labels: automatic-merge
